[build-system]
requires = ["setuptools"]

[tool.setuptools.packages.find]
exclude = ["www"]

[project]
name = "pycupra"
version = "0.1.14"
description="A library to read and send vehicle data via Cupra/Seat portal using the same API calls as the MyCupra/MySeat mobile app."
readme="README.md"
license = "Apache-2.0"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.12"
dependencies = [
    "aiohttp",
    "beautifulsoup4",
    "cryptography",
    "lxml",
    "PyJWT",
    "xmltodict",
    "pandas",
    "pillow",
    "protobuf",
    "http-ece",
    "requests-oauthlib"
]